# panic!宏处理

程序遇到bug 或者 手动调用`panic!` 都会触发`panic`

```rs
fn main() {
    panic!("crash and burn");
}
```

```sh
$ cargo run
   Compiling panic v0.1.0 (file:///projects/panic)
    Finished dev [unoptimized + debuginfo] target(s) in 0.25s
     Running `target/debug/panic`
thread 'main' panicked at 'crash and burn', src/main.rs:2:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

类似输出，可以提示第几行，第几个字符串出错。

还可以通过 `backtrace`来寻找异常位置

## backtrace

由于我们自己程序bug，导致其他库的`panic`...

```rs
fn main() {
    let v = vec![1, 2, 3];

    v[99];
}
```

写一个Bug，读取 vector中无效索引，造成 `buffer overread`缓冲区溢出

```sh
$ cargo run
   Compiling panic v0.1.0 (file:///projects/panic)
    Finished dev [unoptimized + debuginfo] target(s) in 0.27s
     Running `target/debug/panic`
thread 'main' panicked at 'index out of bounds: the len is 3 but the index is 99', src/main.rs:4:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

```sh
RUST_BACKTRACE=1 cargo run
```

在debug模式下，加上`RUST_BACKTRACE`环境变量来运行，就可以看到大量输出，从中就可以发现异常端倪...