# 用Result处理可恢复的错误

```rs
enum Result<T, E> {
    Ok(T),
    Err(E)
}
```

通过打开文件场景，来处理成功和失败情况

```rs
use std::fs::File;

fn main() {
    let file_result = File::open("hello.txt");
}

```

`File::open`成功下，T是成功返回值的类型`std::fs::File`，是一个文件句柄

错误下，返回值类型是 `std::io::Error`


使用`match`处理`Result`成员

```rs
use std::fs::File;

fn main() {
    let file_result = File::open("hello.txt");

    let file = match file_result {
        Ok(file) => file,
        Err(error) => panic!("problem opening the file: {:?}", error),
    };
}
```

# 匹配不同的错误

`File::open`失败原因也要做区分:

```rs
use std::fs::File;
use std::io::ErrorKind;

fn main() {
    let file_result = File::open("hello.txt");

    let file = match file_result {
        Ok(file) => file,
        // Err(error) => panic!("problem opening the file: {:?}", error),
        Err(error) => match error.kind() {
            ErrorKind::NotFound => match File::create("hello.txt") {
                Ok(fc) => fc,
                Err(e) => panic!("problem creating the file: {:?}", e),
            },
            other_error => {
                panic!("problem opening the file: {:?}, other_error");
            }
        }
    };
}
```

`File.open`返回的`Err`成员中的类型`io::Error`，它是一个标准库中提供的结构体。

这个结构体有一个kind方法，返回`ErrorKind`类型是`io::ErrorKind`。

这个`io::ErrorKind`类型是标准库提供的一个枚举，它定义了io操作可能导致的不同错误类型。

其中`ErrorKind::NotFound`代表尝试打开一个不存在的文件

官网还介绍了一个简洁写法：[官网参考](https://kaisery.github.io/trpl-zh-cn/ch09-02-recoverable-errors-with-result.html#%E5%8C%B9%E9%85%8D%E4%B8%8D%E5%90%8C%E7%9A%84%E9%94%99%E8%AF%AF)

```rs
use std::fs::File;
use std::io::ErrorKind;

fn main() {
    let greeting_file = File::open("hello.txt").unwrap_or_else(|error| {
        if error.kind() == ErrorKind::NotFound {
            File::create("hello.txt").unwrap_or_else(|error| {
                panic!("Problem creating the file: {:?}", error);
            })
        } else {
            panic!("Problem opening the file: {:?}", error);
        }
    });
}
```

借助 `unwrap_or_else`仅处理失败错误情况，不使用match表达式，更容易阅读。


# 失败时panic的简写

## unwrap

它是`Result<T, E>`类型提供的辅助方法

如果`Result`值是成员`Ok`，`unwrap`会返回Ok中的值

如果`Result`值是成员`Err`，`unwrap`会调用`panic!`

```rs
use std::fs::File;

fn main() {
    let visit_file = File::open("hello.txt").unwrap();
}
```

```sh
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os {
code: 2, kind: NotFound, message: "No such file or directory" }',
src/main.rs:4:49

```

## expect

它类似`unwrap`，还可以选择`panic!`的错误信息

```rs
use std::fs::File;

fn main() {
    let greeting_file = File::open("hello.txt")
        .expect("hello.txt should be included in this project");
}
```

```sh
thread 'main' panicked at 'hello.txt should be included in this project: Error
{ repr: Os { code: 2, message: "No such file or directory" } }',
src/libcore/result.rs:906:4
```

相比`unwrap`，`expect`更方便调试，错误排查